### ISSUE TITLE
ERROR: Unable to install required packages

### ISSUE THREAD

**Issue by SViktrch** [ianw1974/zimbra-build-scripts#27] opened 2023-08-10 14:03 UTC
After running the ./install.sh script from the zcs-10.0.0_GA_0001.UBUNTU20_64.20230810163311 folder, I get an error at the end:
ERROR: Unable to install required packages
Fix the issues with remote package installation and rerun the installer
Tell me, please, what to do?

Attaching the installation process
[Install_Zimbra.txt](https://github.com/ianw1974/zimbra-build-scripts/files/12313587/Install_Zimbra.txt)

**Comment by ianw1974** [comment] 2023-08-10 15:02
Sounds to me the installation package you downloaded is corrupt and hasn't been downloaded properly.

Did you check the md5sum of the package downloaded and does it match the md5sum that is avaiable on my site? 
Are you installing this on Ubuntu 20.04 or attempting to install it on another version of Ubuntu?

Difficult to tell really, since the output on the screen doesn't tell much in to what the problem is unless it hasn't been copied completely.  Based on that, almost impossible to suggest a solution.  All I can suggest is that you ensure you are installing it on Ubuntu 20.04 and you also ensure that the md5sum **exactly** matches to the one on my site.

**Comment by ianw1974** [comment] 2023-08-10 15:24
This explains the getcwd error: https://stackoverflow.com/questions/12758125/sh-0-getcwd-failed-no-such-file-or-directory-on-cited-drive

Which would suggest the attached output sent is not complete, or was ran from an incorrect location that later caused issues.

**Comment by ianw1974** [comment] 2023-08-10 16:44
So, I just span up a VM to be able to check/test/verify this:

```
root@zimbra:/home/ian# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal
```

I'm not using DNS, so I make sure /etc/hosts resolves my FQDN for this test (usually you should have DNS configured for production):

```
root@zimbra:/home/ian# cat /etc/hosts | grep zimbra.mydomain
192.168.122.185	zimbra.mydomain.local zimbra
```

```
root@zimbra:/home/ian# hostname -f
zimbra.mydomain.local
```

verified md5sum:

```
root@zimbra:/home/ian# md5sum -c zcs-10.0.0_GA_0001.UBUNTU20_64.20230630084357.tgz.md5 
zcs-10.0.0_GA_0001.UBUNTU20_64.20230630084357.tgz: OK
```

I ran the install process, but what I see is yours has this:

```
Removing /opt/zimbra
Removing zimbra crontab entry...done.
sh: 0: getcwd() failed: No such file or directory
Cleaning up zimbra init scripts...done.
Cleaning up /etc/security/limits.conf...sh: 0: getcwd() failed: No such file or directory
done.
```

and mine when it gets to this place:

```
Removing /opt/zimbra
Removing zimbra crontab entry...done.
Cleaning up zimbra init scripts...done.
Cleaning up /etc/security/limits.conf...done.
```

as you can see, mine has worked perfectly.  I have no getcwd error, so I'm not sure what you have done on your server differently.  I downloaded and unpacked the Zimbra package in my home directory of /home/ian - maybe you unpacked it elsewhere perhaps /opt/zimbra that got deleted?  Or you were sitting in a directory on your system that got deleted, when you ran the install script.  Either way, I cannot replicate your problem.

That said I do have this error on mine:

```
Running Post Installation Configuration:
Operations logged to /tmp/zmsetup.20230810-160033.log
Installing LDAP configuration database...done.
Setting defaults...sh: 1: /sbin/ifconfig: not found
```

which is somewhat strange that the installer is using deprecated tools, this would need to be resolved with:

```
apt-get install net-tools
```

however the installer did continue and failed with something else relating to generating SSL certificates and mailboxd (even after installing net-tools so this had no effect on it).  There are Zimbra forum posts that suggest generating with FIPS because something changed - but they relate to existing installs.

This also happens for ZCS-9 on Ubuntu 20.04 for some reason although these builds did work previously.  This would suggest that something has changed that stops this from installing on Ubuntu 20.04 - either from Zimbra side or from Ubuntu side.

I span up a Rocky 8 VM to see if the problem also occurs there.  Some additional requirements there:

```
dnf install -y perl net-tools
```

the problem also occurs on Rocky 8.  There were some OpenSSL bugs fixed recently I believe, so whether they have attributed to this or not, I would have to check into by making some fresh builds to see if they fix the problem or not.

These builds used to work, so something definitely changed somewhere...

**Comment by ianw1974** [comment] 2023-08-10 17:01
I will be continuing on this in issue #28 so please follow this issue.  This issue I will close, since I cannot replicate your problem and can only put it down to a corrupt/failed download.  However since I have found other issues, they will be addressed separately in the linked issue.

**Closed by ianw1974** 2023-08-10 17:01 UTC

**Comment by SViktrch** [comment] 2023-08-11 09:45
> Sounds to me the installation package you downloaded is corrupt and hasn't been downloaded properly.
> 
> Did you check the md5sum of the package downloaded and does it match the md5sum that is avaiable on my site? Are you installing this on Ubuntu 20.04 or attempting to install it on another version of Ubuntu?
> 
> Difficult to tell really, since the output on the screen doesn't tell much in to what the problem is unless it hasn't been copied completely. Based on that, almost impossible to suggest a solution. All I can suggest is that you ensure you are installing it on Ubuntu 20.04 and you also ensure that the md5sum **exactly** matches to the one on my site.

I will answer in order so as not to make a mistake.

From the site I do not download files, I do according to the instructions, namely with the help of your script. I upload files using the command: `./zimbra-build-helper.sh --build-zimbra`
As a result, all files are uploaded to the **/opt/zimbra/** folder, as I indicated in the configuration file.
The Zimbra archive file is located in the **/opt/zimbra/BUILDS** folder.
The downloaded archive using the script has the name: **zcs-10.0.0_GA_0001.UBUNTU20_64.20230811114058.tgz**
The downloaded archive from your site has the name: **zcs-10.0.0_GA_0001.UBUNTU20_64.20230810205347.tgz**
Please tell me how to check md5sum in this case?

System information:
root@mail: lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal

**Comment by ianw1974** [comment] 2023-08-11 09:52
My build process does not use /opt/zimbra unless you created this.  I do not recommend using this directory, since Zimbra will install to /opt/zimbra.  Installation process deletes contents of /opt/zimbra if it exists, so what happened for you is, the extracted installation package zcs*.tgz was deleted and your install failed.

**Comment by SViktrch** [comment] 2023-08-11 09:55
> My build process does not use /opt/zimbra unless you created this. I do not recommend using this directory, since Zimbra will install to /opt/zimbra. Installation process deletes contents of /opt/zimbra if it exists, so what happened for you is, the extracted installation package zcs*.tgz was deleted and your install failed.

Ok, now I will return the configuration file to its original state and check it.
Thank you!

**Comment by SViktrch** [comment] 2023-08-11 11:26
Zimbra is installed and working.
Thanks again for your support!
